#!/usr/bin/env python

"""
Make StationXML files from scratch, given an existing directory of miniSEED files and
metadata generated by cube_convert. Adopted from the ObsPy tutorial here:
    https://docs.obspy.org/tutorial/code_snippets/stationxml_file_from_scratch.html

The code assumes that your sensors are all Chaparral Physics products, and that your
digitizers are all DiGOS DATA-CUBE³s.

Importantly, this code *will not work properly* unless you're using ObsPy after commit
107666b:
    https://github.com/obspy/obspy/tree/107666b9659cbfdc98470a47c003772377551264
(This commit introduced a change that allows for re-computation of the overall
sensitivity for non-standard units — like Pa.) Until the 1.5.0 release of ObsPy comes
out, you can simply update ObsPy via:
    pip install git+https://github.com/obspy/obspy.git
This will fetch and install the newest copy from GitHub.
"""

import argparse
import os

# -----------------------------------------------------------------------------
# Advanced configuration options
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------


# Define callable main function to work with [project.scripts]
def main():

    # Set up command-line interface
    parser = argparse.ArgumentParser(
        description='Generate StationXML files from DATA-CUBE³ miniSEED files and metadata.',
        allow_abbrev=False,
    )
    parser.add_argument(
        'input_dir',
        help='directory containing miniSEED files and coordinate files produced by cube_convert',
    )
    input_args = parser.parse_args()

    # Check if input directory is valid
    if not os.path.exists(input_args.input_dir):
        raise NotADirectoryError(
            f'Input directory \'{input_args.input_dir}\' doesn\'t ' 'exist.'
        )


# Run the main function if this is called as a script
if __name__ == '__main__':
    main()
